/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HolaMundoN */

#ifndef _Included_HolaMundoN
#define _Included_HolaMundoN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HolaMundoN
 * Method:    presentaSaludo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HolaMundoN_presentaSaludo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
